# Generated by Django 5.0.6 on 2024-05-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KyivApartments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flat_id", models.IntegerField(blank=True, null=True)),
                (
                    "area_total",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("built_year", models.IntegerField(blank=True, null=True)),
                ("currency", models.TextField(blank=True, null=True)),
                ("district", models.TextField(blank=True, null=True)),
                ("micro_district", models.TextField(blank=True, null=True)),
                ("street", models.TextField(blank=True, null=True)),
                ("house_number", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("room_count", models.IntegerField(blank=True, null=True)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("insertion_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "kyiv_apartments",
                "managed": False,
            },
        ),
    ]
